---
- name: install packages
  action: apt pkg={{item}} state=present
  with_items:
    - qrencode
    - jq
    - expect
    - rsync
    - gpm
    - ncdu
    - bzip2
    - p7zip
    - strace
    - gdb
    - nano
    - vim-nox
    - emacs-nox
    - parted
    - hwinfo
    - lvm2
    - glances
    - htop
    - tmux
